export const RECEIVE_GRAPH = 'RECEIVE_GRAPH'
export const FETCH_GRAPH = 'FETCH_GRAPH'
export const UPDATE_GRAPH = 'UPDATE_GRAPH'
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
